### ISSUE TITLE
Consumption: Indicate the time frame (month or year)

### ISSUE THREAD

**Issue by zweiro** [MediaComem/bytesim-webapp#10]
Specify the time frame as "per month" in the "number of visits" settings as well as in the energy / GWP emissions panels. The calculation should already be correctly implemented.

**Comment by MathildeIgier** [comment]
@zweiro, I don't understand what is it about

**Comment by zweiro** [comment]
@MathildeIgier I've updated the main comment. I hope it answers your question.

**Comment by zweiro** [comment]
@MathildeIgier I've updated the main comment. I hope it answers your question.

**Comment by MathildeIgier** [comment]
https://github.com/MediaComem/bytesim-webapp/pull/40
