### ISSUE TITLE
Optimize components rendering

### ISSUE THREAD

**Issue by zweiro** [MediaComem/bytesim-webapp#116]

**Comment by slecorne** [comment]
Forms of each zone does not need to be render (although hidden) as long as it is not clicked to be open. That would probably improve a lot the performances by reducing the DOM size if the region form was only created once a region is opened

**Comment by slecorne** [comment]
ex: https://mediacomem.github.io/bytesim-webapp/#/figma?key=nHnhsEAipy6VWZA6WshkMK_bytesimtest3.svg
opening a region takes more than 1 sec
