### ISSUE TITLE
Change label on upload "artwork" button

### ISSUE THREAD

**Issue by lobollo** [MediaComem/bytesim-webapp#117]
Artwork is not a clear label -> change it for "SVG format"

Button "Import Artwork" -> "Import SVG file"
Label "Upload Artwork" -> "Upload your .svg file"
Label inside upload zone "Drag and Drop a file, or click to select a file" - > "Click to select your .svg file"

**Comment by slecorne** [comment]
no need if we allow upload jpg/png

**Comment by zweiro** [comment]
Is it still relevant as the user should be able to import png and jpeg as well.

**Comment by zweiro** [comment]
This issue will be fixed by #118.
