### ISSUE TITLE
screenshot for zone recommandation wrong

### ISSUE THREAD

**Issue by slecorne** [MediaComem/bytesim-webapp#124]
at least for that one https://mediacomem.github.io/bytesim-webapp/#/figma?key=nHnhsEAipy6VWZA6WshkMK_bytesimtest3.svg

**Comment by GaspardC** [comment]
@slecorne on which component did you experience a pb? 
it seems to be working on this example


<img width="1353" alt="Screenshot 2023-02-27 at 14 05 48" src="https://user-images.githubusercontent.com/9252579/221571421-d6ca1828-3491-4211-9359-319222a99ad7.png">

**Comment by slecorne** [comment]
it was not working when we tried with Robin last time but I cannot reproduce it indeed. Assuming OK
