### ISSUE TITLE
zone image (imported zone) need to explicitely change number of images

### ISSUE THREAD

**Issue by slecorne** [MediaComem/bytesim-webapp#125]

**Comment by slecorne** [comment]
* select one imported zone
* select type image
* set format + size => zone incomplete
* change number from 1 to 2 => OK

zone should be considered complete as soon as format + size done

**Comment by GaspardC** [comment]
@slecorne It looks like it has already been solved

**Comment by slecorne** [comment]
on my side, it works if you create a new zone but it does not work if you set a zone imported from svg as image

**Comment by GaspardC** [comment]
what I am not testing correctly? 

https://user-images.githubusercontent.com/9252579/223387278-6b960b13-2ab3-455b-bcef-e6658c1283ee.mov

**Comment by GaspardC** [comment]
ok, I managed to reproduce the issue with another imported file,
I'll look into it :)
<img width="1334" alt="Screenshot 2023-03-07 at 11 04 22" src="https://user-images.githubusercontent.com/9252579/223389817-913226b8-adaf-48c4-a2b9-0caba4d58e10.png">
