### ISSUE TITLE
Report: show each recommendation gains

### ISSUE THREAD

**Issue by zweiro** [MediaComem/bytesim-webapp#30]
show recommandation gain + show negative impact if back to original 

ex: no recommandation selected
* video 1080P (selected) 
* sober 720P -1kgCo2eq 
* most sober 480p -3kg Co2eq

ex: sober selected
* video 1080P + 1kgCo2eq
* sober 720P (selected)
* most sober 480P -2kg Co2eq

**Comment by GaspardC** [comment]
@zweiro is the gain/loss already available or not yet?  (ex -2kg Co2eq)

**Comment by slecorne** [comment]
not yet, we will be working on it in the next days

**Comment by slecorne** [comment]
actually, I checked and I think the information should be there already.
There are 2 objects in the `Recommandation`:

- `benefitsBetter` that contains the benefits if better is selected (co2/energy)
- `benefitsBest` that contains the benefits if best is selected (co2/energy)

Both benefits are compared to current. So the logic should be:
- current selected:
  - better -> display benefitsBetter.co2
  - best -> display BenefitsBest.co2
- better selected
  - current -> display - benefitsBetter.co2
  - best -> display benefitsBest.co2 - BenefitsBetter.co2
- best selected
  - current -> display -BenefitsBest.co2
  - better -> display BenefitsBetter.co2 - benefitsBest.co2

**Comment by MathildeIgier** [comment]
![Image](https://user-images.githubusercontent.com/44711385/202459700-da6ba79e-d0e6-4608-bfa4-e70d581356e0.png)

I have questions & remarks about this functionality:
- we always have benefitsBetter and benefitsBest returning values around 0 event when the overall GWP gain is big
- from what I understood, this values should be updated if the user is playing with the recommandations but the recommandation stays the same

**Comment by slecorne** [comment]
values are per zone per visitor, so it has to be multiplied by the number of visitors I think
