### ISSUE TITLE
Limit screenshots size

### ISSUE THREAD

**Issue by zweiro** [MediaComem/bytesim-webapp#73]
- [ ] Fix max-height to 40px
- [ ] Fix max-width to 25%

**Comment by slecorne** [comment]
Ideally display bigger screenshot on hover

**Comment by MathildeIgier** [comment]
Are we keeping this metrics with the screenshot emplacement ?
The height is the same as the text and the max width is 40%


![Image](https://user-images.githubusercontent.com/44711385/203957117-03e7f596-ee86-40af-8e8e-a11491031d94.png)

**Comment by slecorne** [comment]
looks good for beta version
