### ISSUE TITLE
Remove zoom and replace it with "Fit height/width" buttons

### ISSUE THREAD

**Issue by zweiro** [MediaComem/bytesim-webapp#75]
### Zoom

- [ ] Remove actual slider
- [ ] Replace it by to buttons: "Fit height" and "Fit width"
- [ ] Create related behaviors
- [ ] Offer scroll on overflow

**Comment by GaspardC** [comment]
@zweiro just to be sure before coding it, 
you would like to remove the continuous zoom but have only to option "Fit by height" and "Fit by width" ? 

and both for imported zones as well as drawn zones

**Comment by zweiro** [comment]
@GaspardC exactly ! To keep only "Fit by height" and "Fit by width" for both imported and drawn zones.

**Comment by zweiro** [comment]
#115
