### ISSUE TITLE
Update to fit design

### ISSUE THREAD

**Issue by slecorne** [MediaComem/bytesim-webapp#77]

**Comment by MathildeIgier** [comment]
https://github.com/MediaComem/bytesim-webapp/pull/80

**Comment by audreyhuguenin** [comment]
To do:

- [ ] Reduce spaces in forms
- [ ] Reduce font size in Headers
- [ ] Adapt font sizes in forms
- [ ] Boldness of forms headers
- [ ] Margin Left in forms
- [ ] make all option box same (html el. + accent color pink)
- [ ] (make font inter UI)
