### ISSUE TITLE
Recommendations user's choices are reset when a zone is modified

### ISSUE THREAD

**Issue by zweiro** [MediaComem/bytesim-webapp#87]
To reproduce the bug:

- Create and fill two zones
- Choose a more sober setting in the recommendations of a zone
- Change the settings of a zone (on the left)
--> All recommendations are reset

**Comment by zweiro** [comment]
Recommendations user's choices are also reset when coming back from the report.

**Comment by MathildeIgier** [comment]
https://github.com/MediaComem/bytesim-webapp/pull/91
